USE [master]
GO

/****** Object:  Database [AddressBookDB]    Script Date: 5/2/2020 7:59:28 PM ******/
IF EXISTS (SELECT 1 FROM sys.databases WHERE NAME='AddressBookDB')
       DROP DATABASE [AddressBookDB];

/****** Object:  Database [AddressBookDB]    Script Date: 5/2/2020 7:59:28 PM ******/
CREATE DATABASE  [AddressBookDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AddressBookDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AddressBookDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AddressBookDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AddressBookDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AddressBookDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AddressBookDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AddressBookDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AddressBookDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AddressBookDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AddressBookDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AddressBookDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AddressBookDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AddressBookDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AddressBookDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AddressBookDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AddressBookDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AddressBookDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AddressBookDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AddressBookDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AddressBookDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AddressBookDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AddressBookDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AddressBookDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AddressBookDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AddressBookDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AddressBookDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AddressBookDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AddressBookDB] SET RECOVERY FULL 
GO

ALTER DATABASE [AddressBookDB] SET  MULTI_USER 
GO

ALTER DATABASE [AddressBookDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AddressBookDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AddressBookDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AddressBookDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AddressBookDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AddressBookDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AddressBookDB] SET  READ_WRITE 
GO

